sudo: required
services:
  - docker

before_install:
  - docker build -t showy93/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true showy93/react-test npm test

after_success:
  - docker build -t showy93/multi-client ./client
  - docker build -t showy93/multi-nginx ./nginx
  - docker build -t showy93/multi-server ./server
  - docker build -t showy93/multi-worker ./worker
  # Take those images and push them to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push showy93/multi-client
  - docker push showy93/multi-nginx
  - docker push showy93/multi-server
  - docker push showy93/multi-worker

  deploy:
    provider: elasticbeanstalk
    region: 'eu-central-1'
    app: 'multi-docker'
    env: 'Multidocker-env'
    bucket_name: 'elasticbeanstalk-eu-central-1-824372718429'
    bucket_path: 'docker-multi'
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY